import esbuild from "esbuild";
import process from "process";
import builtinModules from "builtin-modules";
import sveltePlugin from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";

let vaultExportPlugin = [];
try {
  const { createVaultExportPlugin } = await import("@denkarium/esbuild-vault-export");
  vaultExportPlugin = [createVaultExportPlugin()];
} catch {
  // optional: install @denkarium/esbuild-vault-export for watch → /vault
}

const banner =
  `/*\n` +
  `THIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n` +
  `If you want to view the source, please visit the github repository of this plugin\n` +
  `*/\n`;

const watch = process.argv.includes("--watch");

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  plugins: [
    sveltePlugin({
      preprocess: sveltePreprocess(),
      compileOptions: {
        css: "injected",
        dev: watch,
      },
    }),
    ...vaultExportPlugin,
  ],
  external: ["obsidian", "electron", ...builtinModules],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: false,
  treeShaking: true,
  outfile: "main.js",
});

if (watch) {
  await context.watch();
  // eslint-disable-next-line no-console
  console.log("watching...");
} else {
  await context.rebuild();
  await context.dispose();
}
